# Generated by Django 4.1.7 on 2023-11-08 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Минимальная сумма')),
                ('max_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Максимальная сумма')),
                ('wallet_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес кошелька')),
                ('tm_chat_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телеграмм чат ID')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('zip_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='Индекс')),
                ('is_active', models.BooleanField(default=True, verbose_name='Пользователь не удален')),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(blank=True, choices=[('manager', 'Менеджер'), ('buyer', 'Покупатель'), ('seller', 'Продавец')], max_length=10, null=True, verbose_name='Роль пользователя')),
                ('mode_issue', models.BooleanField(default=False, verbose_name='Режим сделок')),
                ('auth_key', models.CharField(max_length=36, unique=True)),
                ('crypto_balance', models.DecimalField(decimal_places=8, default=0.0, max_digits=12, verbose_name='Баланс Bitcoin')),
                ('state', models.BooleanField(default=False, verbose_name='Активация')),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('USD', 'USD')], default='USD', max_length=7)),
                ('unique_uid', models.TextField(default='None')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_groups', to='auth.group')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.profile', verbose_name='Профиль')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
