# Generated by Django 4.2.7 on 2023-11-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_customuser_is_active_alter_customuser_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активная')),
                ('description', models.CharField(max_length=600, verbose_name='Описание')),
                ('type_pay_system', models.CharField(blank=True, max_length=120, null=True, verbose_name='Тип платежной системы')),
                ('country', models.CharField(default='Rus', max_length=20, verbose_name='Страна платежной системы')),
                ('as_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ManyToManyField(related_name='pay_systems', to='users.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платежная система',
                'verbose_name_plural': 'Платежные системы',
                'db_table': 'pay_system',
            },
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=120, verbose_name='Данные реквизитов')),
                ('payment_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='pay_sys.paysystem', verbose_name='Платежная система')),
                ('user', models.ManyToManyField(related_name='requisites', to='users.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
                'db_table': 'requisites',
            },
        ),
    ]
