# Generated by Django 4.2.7 on 2023-11-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pay_sys', '0001_initial'),
        ('users', '0002_alter_customuser_is_active_alter_customuser_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('amount', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('discussion', 'В споре'), ('paid', 'Олачено'), ('completed', 'Завершена'), ('in_processing_paid', 'В ожидании оплаты'), ('work_manager', 'В обработке менеджером'), ('canceled', 'Отменена'), ('check_seller', 'На подтверждении у продавца'), ('found_buyer', 'В поиске продавца')], default='В поиске продавца', max_length=25)),
                ('buyer_yes', models.BooleanField(default=False, verbose_name='Согласие ')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('date_paid', models.DateTimeField(auto_now_add=True, verbose_name='Дата оплаты')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_buy', to='users.customuser', verbose_name='Покупатель')),
                ('pay_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pay_sys.paysystem', verbose_name='Платежная система продавца')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sell', to='users.customuser', verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'db_table': 'transactions',
            },
        ),
    ]
