# Generated by Django 4.2.7 on 2023-11-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_data', models.CharField(max_length=1000, verbose_name='Зпрошенные данные менеджером')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания спора')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Комментарий')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Разрешено')),
                ('date_completed', models.DateTimeField(auto_now_add=True, verbose_name='Дата разрешения')),
                ('transactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.transactions', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Спор',
                'verbose_name_plural': 'Споры',
                'db_table': 'discussions',
            },
        ),
    ]
